server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/quartz_demo
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      pool-name: HikariCP
      maximum-pool-size: 5
      minimum-idle: 5
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        highlight_sql: true

  quartz:
    job-store-type: jdbc
    jdbc:
      initialize-schema: always
      schema: classpath:schema.sql
    properties:
      org:
        quartz:
          jobStore:
            tablePrefix: QUARTZ_
          threadPool:
            threadCount: 5