spring:
  datasource:
    url: jdbc:mysql://localhost:3306/quartz_demo
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      pool-name: HikariCP
      maximum-pool-size: 5
      minimum-idle: 5
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        highlight_sql: true

  quartz:
    properties:
      org:
        quartz:
          threadPool:
            threadCount: 5