server:
  port: 8080

spring:
  application:
    name: SpringSecurityDemo

  datasource:
    url: jdbc:mysql://localhost:3306/spring_security_demo
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      pool-name: HikariCP
      maximum-pool-size: 5
      minimum-idle: 5
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        highlight_sql: true
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      database: 0
      timeout: 1000ms
      password:
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
          max-wait: -1ms