mybatis-flex:
  datasource:
    postgres_one:
      url: jdbc:postgresql://localhost:5432/mybatis_flex_one
      username: mybatis_flex_one
      password: password
      type: hikari
      minimum-idle: 3
      maximum-pool-size: 5
      driver-class-name: org.postgresql.Driver

    postgres_two:
      url: jdbc:postgresql://localhost:5433/mybatis_flex_two
      username: mybatis_flex_two
      password: password
      type: hikari
      minimum-idle: 3
      maximum-pool-size: 5
      driver-class-name: org.postgresql.Driver

  global-config:
    print-banner: false

  generate:
    ddl: false
