server:
  port: 8080

spring:
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
      continue-on-error: true

  datasource:
    url: jdbc:postgresql://localhost:5432/githubCiCD
    username: githubCiCD
    password: password
    driver-class-name: org.postgresql.Driver
    hikari:
      minimum-idle: 3
      maximum-pool-size: 5

generate:
  ddl: false