services:
  postgres_one:
    image: postgres:16.4
    container_name: postgres_one
    environment:
      POSTGRES_USER: mybatis_flex_one
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mybatis_flex_one
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_one_schema.sql:/docker-entrypoint-initdb.d/init.sql

  postgres_two:
    image: postgres:16.4
    container_name: postgres_two
    environment:
      POSTGRES_USER: mybatis_flex_two
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mybatis_flex_two
    ports:
      - "5433:5432"
    volumes:
      - ./postgres_two_schema.sql:/docker-entrypoint-initdb.d/init.sql

  mybatis_flex_demo:
    image: maifuwa/mybatis-flex-demo:1.0.0
    container_name: mybatis_flex_demo
    depends_on:
      - postgres_one
      - postgres_two
    ports:
      - "8080:8080"